# Generated by Django 5.1.6 on 2026-04-18 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Demande envoyée'), ('ACCEPTED', 'Acceptée par le transporteur'), ('PICKED_UP', 'Colis récupéré'), ('IN_TRANSIT', 'En cours de route'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé')], default='REQUESTED', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order')),
                ('transporter', models.ForeignKey(limit_choices_to={'role': 'TRANSPORTER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_to_handle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
