# Generated by Django 5.1.6 on 2026-04-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='description',
            field=models.TextField(blank=True, help_text='Contenu du colis', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.CharField(blank=True, help_text='Lieu de livraison', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin',
            field=models.CharField(blank=True, help_text='Lieu de ramassage', max_length=255, null=True),
        ),
    ]
