# Generated by Django 5.1.6 on 2026-04-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_shipment_client_shipment_shipment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Poids en kg', max_digits=10),
        ),
    ]
