# Generated by Django 5.1.6 on 2026-04-18 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_shipment_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='verification_code',
            field=models.CharField(blank=True, help_text='Code pour valider la livraison', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Ville de départ', max_length=100)),
                ('destination', models.CharField(help_text="Ville d'arrivée", max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='Ex: Hebdomadaire, Quotidien', max_length=100, null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
