# Generated by Django 5.2.13 on 2026-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_shipment_verification_code_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='category_prices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='route',
            name='pricing_mode',
            field=models.CharField(choices=[('flat', 'Flat'), ('per_category', 'Per Category')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='product_exceptions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
