# Generated by Django 5.2.13 on 2026-08-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motif de rejet"
            ),
        ),
    ]
