# Generated by Django 5.2.13 on 2026-08-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_product_id_order_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_delegated',
            field=models.BooleanField(default=False),
        ),
    ]
