# Generated by Django 5.1.6 on 2026-04-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(choices=[('Ghana', 'Ghana'), ('Sénégal', 'Sénégal'), ('Maroc', 'Maroc'), ("Côte d'Ivoire", "Côte d'Ivoire"), ('Kenya', 'Kenya'), ('Éthiopie', 'Éthiopie'), ('Nigeria', 'Nigeria'), ('Mali', 'Mali')], default='Sénégal', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(default='', verbose_name='Description (FR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fr',
            field=models.CharField(default='', max_length=255, verbose_name='Nom (FR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='span',
            field=models.CharField(choices=[('square', 'Carré'), ('tall', 'Vertical'), ('wide', 'Large'), ('large', 'Grand Carré')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tag (EN)'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_fr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tag (FR)'),
        ),
    ]
